# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(575, 680)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_uno = QtWidgets.QPushButton(self.centralwidget)
        self.btn_uno.setGeometry(QtCore.QRect(10, 10, 61, 51))
        self.btn_uno.setText("")
        self.btn_uno.setObjectName("btn_uno")
        self.btn_uno.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_due = QtWidgets.QPushButton(self.centralwidget)
        self.btn_due.setGeometry(QtCore.QRect(80, 10, 61, 51))
        self.btn_due.setText("")
        self.btn_due.setObjectName("btn_due")
        self.btn_due.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_tre = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tre.setGeometry(QtCore.QRect(150, 10, 61, 51))
        self.btn_tre.setText("")
        self.btn_tre.setObjectName("btn_tre")
        self.btn_tre.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_quattro = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quattro.setGeometry(QtCore.QRect(220, 10, 61, 51))
        self.btn_quattro.setText("")
        self.btn_quattro.setObjectName("btn_quattro")
        self.btn_quattro.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_cinque = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cinque.setGeometry(QtCore.QRect(290, 10, 61, 51))
        self.btn_cinque.setText("")
        self.btn_cinque.setObjectName("btn_cinque")
        self.btn_cinque.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_sei = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sei.setGeometry(QtCore.QRect(360, 10, 61, 51))
        self.btn_sei.setText("")
        self.btn_sei.setObjectName("btn_sei")
        self.btn_sei.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_sette = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sette.setGeometry(QtCore.QRect(430, 10, 61, 51))
        self.btn_sette.setText("")
        self.btn_sette.setObjectName("btn_sette")
        self.btn_sette.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_otto = QtWidgets.QPushButton(self.centralwidget)
        self.btn_otto.setGeometry(QtCore.QRect(500, 10, 61, 51))
        self.btn_otto.setText("")
        self.btn_otto.setObjectName("btn_otto")
        self.btn_otto.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_nove = QtWidgets.QPushButton(self.centralwidget)
        self.btn_nove.setGeometry(QtCore.QRect(10, 70, 61, 51))
        self.btn_nove.setText("")
        self.btn_nove.setObjectName("btn_nove")
        self.btn_nove.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_dieci = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dieci.setGeometry(QtCore.QRect(80, 70, 61, 51))
        self.btn_dieci.setText("")
        self.btn_dieci.setObjectName("btn_dieci")
        self.btn_dieci.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_undici = QtWidgets.QPushButton(self.centralwidget)
        self.btn_undici.setGeometry(QtCore.QRect(150, 70, 61, 51))
        self.btn_undici.setText("")
        self.btn_undici.setObjectName("btn_undici")
        self.btn_undici.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_dodici = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dodici.setGeometry(QtCore.QRect(220, 70, 61, 51))
        self.btn_dodici.setText("")
        self.btn_dodici.setObjectName("btn_dodici")
        self.btn_dodici.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_tredici = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tredici.setGeometry(QtCore.QRect(290, 70, 61, 51))
        self.btn_tredici.setText("")
        self.btn_tredici.setObjectName("btn_tredici")
        self.btn_tredici.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_quattordici = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quattordici.setGeometry(QtCore.QRect(360, 70, 61, 51))
        self.btn_quattordici.setText("")
        self.btn_quattordici.setObjectName("btn_quattordici")
        self.btn_quattordici.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_quindici = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quindici.setGeometry(QtCore.QRect(430, 70, 61, 51))
        self.btn_quindici.setText("")
        self.btn_quindici.setObjectName("btn_quindici")
        self.btn_quindici.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_sedici = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sedici.setGeometry(QtCore.QRect(500, 70, 61, 51))
        self.btn_sedici.setText("")
        self.btn_sedici.setObjectName("btn_sedici")
        self.btn_sedici.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_diciassette = QtWidgets.QPushButton(self.centralwidget)
        self.btn_diciassette.setGeometry(QtCore.QRect(10, 130, 61, 51))
        self.btn_diciassette.setText("")
        self.btn_diciassette.setObjectName("btn_diciassette")
        self.btn_diciassette.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_diciotto = QtWidgets.QPushButton(self.centralwidget)
        self.btn_diciotto.setGeometry(QtCore.QRect(80, 130, 61, 51))
        self.btn_diciotto.setText("")
        self.btn_diciotto.setObjectName("btn_diciotto")
        self.btn_diciotto.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_diciannove = QtWidgets.QPushButton(self.centralwidget)
        self.btn_diciannove.setGeometry(QtCore.QRect(150, 130, 61, 51))
        self.btn_diciannove.setText("")
        self.btn_diciannove.setObjectName("btn_diciannove")
        self.btn_diciannove.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_venti = QtWidgets.QPushButton(self.centralwidget)
        self.btn_venti.setGeometry(QtCore.QRect(220, 130, 61, 51))
        self.btn_venti.setText("")
        self.btn_venti.setObjectName("btn_venti")
        self.btn_venti.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_ventuno = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ventuno.setGeometry(QtCore.QRect(290, 130, 61, 51))
        self.btn_ventuno.setText("")
        self.btn_ventuno.setObjectName("btn_ventuno")
        self.btn_ventuno.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_ventidue = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ventidue.setGeometry(QtCore.QRect(360, 130, 61, 51))
        self.btn_ventidue.setText("")
        self.btn_ventidue.setObjectName("btn_ventidue")
        self.btn_ventidue.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_ventitre = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ventitre.setGeometry(QtCore.QRect(430, 130, 61, 51))
        self.btn_ventitre.setText("")
        self.btn_ventitre.setObjectName("btn_ventitre")
        self.btn_ventitre.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_ventiquattro = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ventiquattro.setGeometry(QtCore.QRect(500, 130, 61, 51))
        self.btn_ventiquattro.setText("")
        self.btn_ventiquattro.setObjectName("btn_ventiquattro")
        self.btn_ventiquattro.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_venticinque = QtWidgets.QPushButton(self.centralwidget)
        self.btn_venticinque.setGeometry(QtCore.QRect(10, 190, 61, 51))
        self.btn_venticinque.setText("")
        self.btn_venticinque.setObjectName("btn_venticinque")
        self.btn_venticinque.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_ventisei = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ventisei.setGeometry(QtCore.QRect(80, 190, 61, 51))
        self.btn_ventisei.setText("")
        self.btn_ventisei.setObjectName("btn_ventisei")
        self.btn_ventisei.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_ventisette = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ventisette.setGeometry(QtCore.QRect(150, 190, 61, 51))
        self.btn_ventisette.setText("")
        self.btn_ventisette.setObjectName("btn_ventisette")
        self.btn_ventisette.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_ventotto = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ventotto.setGeometry(QtCore.QRect(220, 190, 61, 51))
        self.btn_ventotto.setText("")
        self.btn_ventotto.setObjectName("btn_ventotto")
        self.btn_ventotto.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_ventinove = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ventinove.setGeometry(QtCore.QRect(290, 190, 61, 51))
        self.btn_ventinove.setText("")
        self.btn_ventinove.setObjectName("btn_ventinove")
        self.btn_ventinove.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_trenta = QtWidgets.QPushButton(self.centralwidget)
        self.btn_trenta.setGeometry(QtCore.QRect(360, 190, 61, 51))
        self.btn_trenta.setText("")
        self.btn_trenta.setObjectName("btn_trenta")
        self.btn_trenta.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_trentuno = QtWidgets.QPushButton(self.centralwidget)
        self.btn_trentuno.setGeometry(QtCore.QRect(430, 190, 61, 51))
        self.btn_trentuno.setText("")
        self.btn_trentuno.setObjectName("btn_trentuno")
        self.btn_trentuno.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_trentadue = QtWidgets.QPushButton(self.centralwidget)
        self.btn_trentadue.setGeometry(QtCore.QRect(500, 190, 61, 51))
        self.btn_trentadue.setText("")
        self.btn_trentadue.setObjectName("btn_trentadue")
        self.btn_trentadue.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_trentatre = QtWidgets.QPushButton(self.centralwidget)
        self.btn_trentatre.setGeometry(QtCore.QRect(10, 250, 61, 51))
        self.btn_trentatre.setText("")
        self.btn_trentatre.setObjectName("btn_trentatre")
        self.btn_trentatre.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_trentaquattro = QtWidgets.QPushButton(self.centralwidget)
        self.btn_trentaquattro.setGeometry(QtCore.QRect(80, 250, 61, 51))
        self.btn_trentaquattro.setText("")
        self.btn_trentaquattro.setObjectName("btn_trentaquattro")
        self.btn_trentaquattro.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_trentacinque = QtWidgets.QPushButton(self.centralwidget)
        self.btn_trentacinque.setGeometry(QtCore.QRect(150, 250, 61, 51))
        self.btn_trentacinque.setText("")
        self.btn_trentacinque.setObjectName("btn_trentacinque")
        self.btn_trentacinque.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_trentasei = QtWidgets.QPushButton(self.centralwidget)
        self.btn_trentasei.setGeometry(QtCore.QRect(220, 250, 61, 51))
        self.btn_trentasei.setText("")
        self.btn_trentasei.setObjectName("btn_trentasei")
        self.btn_trentasei.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_trentasette = QtWidgets.QPushButton(self.centralwidget)
        self.btn_trentasette.setGeometry(QtCore.QRect(290, 250, 61, 51))
        self.btn_trentasette.setText("")
        self.btn_trentasette.setObjectName("btn_trentasette")
        self.btn_trentasette.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_trentotto = QtWidgets.QPushButton(self.centralwidget)
        self.btn_trentotto.setGeometry(QtCore.QRect(360, 250, 61, 51))
        self.btn_trentotto.setText("")
        self.btn_trentotto.setObjectName("btn_trentotto")
        self.btn_trentotto.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_trentanove = QtWidgets.QPushButton(self.centralwidget)
        self.btn_trentanove.setGeometry(QtCore.QRect(430, 250, 61, 51))
        self.btn_trentanove.setText("")
        self.btn_trentanove.setObjectName("btn_trentanove")
        self.btn_trentanove.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_quaranta = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quaranta.setGeometry(QtCore.QRect(500, 250, 61, 51))
        self.btn_quaranta.setText("")
        self.btn_quaranta.setObjectName("btn_quaranta")
        self.btn_quaranta.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_quarantuno = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quarantuno.setGeometry(QtCore.QRect(10, 310, 61, 51))
        self.btn_quarantuno.setText("")
        self.btn_quarantuno.setObjectName("btn_quarantuno")
        self.btn_quarantuno.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_quarantadue = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quarantadue.setGeometry(QtCore.QRect(80, 310, 61, 51))
        self.btn_quarantadue.setText("")
        self.btn_quarantadue.setObjectName("btn_quarantadue")
        self.btn_quarantadue.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_quarantatre = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quarantatre.setGeometry(QtCore.QRect(150, 310, 61, 51))
        self.btn_quarantatre.setText("")
        self.btn_quarantatre.setObjectName("btn_quarantatre")
        self.btn_quarantatre.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_quarantaquattro = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quarantaquattro.setGeometry(QtCore.QRect(220, 310, 61, 51))
        self.btn_quarantaquattro.setText("")
        self.btn_quarantaquattro.setObjectName("btn_quarantaquattro")
        self.btn_quarantaquattro.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_quarantacinque = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quarantacinque.setGeometry(QtCore.QRect(290, 310, 61, 51))
        self.btn_quarantacinque.setText("")
        self.btn_quarantacinque.setObjectName("btn_quarantacinque")
        self.btn_quarantacinque.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_quarantasei = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quarantasei.setGeometry(QtCore.QRect(360, 310, 61, 51))
        self.btn_quarantasei.setText("")
        self.btn_quarantasei.setObjectName("btn_quarantasei")
        self.btn_quarantasei.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_quarantasette = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quarantasette.setGeometry(QtCore.QRect(430, 310, 61, 51))
        self.btn_quarantasette.setText("")
        self.btn_quarantasette.setObjectName("btn_quarantasette")
        self.btn_quarantasette.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_quarantotto = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quarantotto.setGeometry(QtCore.QRect(500, 310, 61, 51))
        self.btn_quarantotto.setText("")
        self.btn_quarantotto.setObjectName("btn_quarantotto")
        self.btn_quarantotto.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_quarantanove = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quarantanove.setGeometry(QtCore.QRect(10, 370, 61, 51))
        self.btn_quarantanove.setText("")
        self.btn_quarantanove.setObjectName("btn_quarantanove")
        self.btn_quarantanove.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_cinquanta = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cinquanta.setGeometry(QtCore.QRect(80, 370, 61, 51))
        self.btn_cinquanta.setText("")
        self.btn_cinquanta.setObjectName("btn_cinquanta")
        self.btn_cinquanta.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_cinquantuno = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cinquantuno.setGeometry(QtCore.QRect(150, 370, 61, 51))
        self.btn_cinquantuno.setText("")
        self.btn_cinquantuno.setObjectName("btn_cinquantuno")
        self.btn_cinquantuno.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_cinquantadue = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cinquantadue.setGeometry(QtCore.QRect(220, 370, 61, 51))
        self.btn_cinquantadue.setText("")
        self.btn_cinquantadue.setObjectName("btn_cinquantadue")
        self.btn_cinquantadue.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_cinquantatre = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cinquantatre.setGeometry(QtCore.QRect(290, 370, 61, 51))
        self.btn_cinquantatre.setText("")
        self.btn_cinquantatre.setObjectName("btn_cinquantatre")
        self.btn_cinquantatre.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_cinquantaquattro = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cinquantaquattro.setGeometry(QtCore.QRect(360, 370, 61, 51))
        self.btn_cinquantaquattro.setText("")
        self.btn_cinquantaquattro.setObjectName("btn_cinquantaquattro")
        self.btn_cinquantaquattro.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_cinquantacinque = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cinquantacinque.setGeometry(QtCore.QRect(430, 370, 61, 51))
        self.btn_cinquantacinque.setText("")
        self.btn_cinquantacinque.setObjectName("btn_cinquantacinque")
        self.btn_cinquantacinque.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_cinquantasei = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cinquantasei.setGeometry(QtCore.QRect(500, 370, 61, 51))
        self.btn_cinquantasei.setText("")
        self.btn_cinquantasei.setObjectName("btn_cinquantasei")
        self.btn_cinquantasei.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_cinquantasette = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cinquantasette.setGeometry(QtCore.QRect(10, 430, 61, 51))
        self.btn_cinquantasette.setText("")
        self.btn_cinquantasette.setObjectName("btn_cinquantasette")
        self.btn_cinquantasette.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_cinquantotto = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cinquantotto.setGeometry(QtCore.QRect(80, 430, 61, 51))
        self.btn_cinquantotto.setText("")
        self.btn_cinquantotto.setObjectName("btn_cinquantotto")
        self.btn_cinquantotto.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_cinquantanove = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cinquantanove.setGeometry(QtCore.QRect(150, 430, 61, 51))
        self.btn_cinquantanove.setText("")
        self.btn_cinquantanove.setObjectName("btn_cinquantanove")
        self.btn_cinquantanove.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_sessanta = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sessanta.setGeometry(QtCore.QRect(220, 430, 61, 51))
        self.btn_sessanta.setText("")
        self.btn_sessanta.setObjectName("btn_sessanta")
        self.btn_sessanta.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_sessantuno = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sessantuno.setGeometry(QtCore.QRect(290, 430, 61, 51))
        self.btn_sessantuno.setText("")
        self.btn_sessantuno.setObjectName("btn_sessantuno")
        self.btn_sessantuno.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_sessantadue = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sessantadue.setGeometry(QtCore.QRect(360, 430, 61, 51))
        self.btn_sessantadue.setText("")
        self.btn_sessantadue.setObjectName("btn_sessantadue")
        self.btn_sessantadue.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_sessantatre = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sessantatre.setGeometry(QtCore.QRect(430, 430, 61, 51))
        self.btn_sessantatre.setText("")
        self.btn_sessantatre.setObjectName("btn_sessantatre")
        self.btn_sessantatre.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_sessantaquattro = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sessantaquattro.setGeometry(QtCore.QRect(500, 430, 61, 51))
        self.btn_sessantaquattro.setText("")
        self.btn_sessantaquattro.setObjectName("btn_sessantaquattro")
        self.btn_sessantaquattro.setStyleSheet('background-color:#C0C0C0;color:#000000;')
        self.btn_generate_code = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generate_code.setGeometry(QtCore.QRect(20, 510, 151, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_generate_code.setFont(font)
        self.btn_generate_code.setObjectName("btn_generate_code")
        self.txt_array_result = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_array_result.setGeometry(QtCore.QRect(200, 510, 361, 87))
        self.txt_array_result.setObjectName("txt_array_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_generate_code.setText(_translate("MainWindow", "Generate Code"))
